import { AppDefinition, AppId } from '@/types/window'
import { DesktopItem } from '@/types/desktop'

export const APP_REGISTRY: Record<AppId, AppDefinition> = {
  finder: {
    id: 'finder',
    name: 'Projects',
    icon: 'folder',
    defaultTitle: 'Projects — Finder',
    defaultWidth: 920,
    defaultHeight: 580,
    minWidth: 540,
    minHeight: 380,
    singleton: true,
    dockItem: true,
    desktopItem: true,
    description: 'Browse all dynamic projects from the database',
  },
  'project-detail': {
    id: 'project-detail',
    name: 'Project Detail',
    icon: 'code',
    defaultTitle: 'Project Details',
    defaultWidth: 840,
    defaultHeight: 580,
    minWidth: 480,
    minHeight: 400,
    singleton: false,
    dockItem: false,
    desktopItem: false,
    description: 'View full project overview, architecture, and links',
  },
  'project-form': {
    id: 'project-form',
    name: 'Project Editor',
    icon: 'edit',
    defaultTitle: 'New Project',
    defaultWidth: 700,
    defaultHeight: 640,
    minWidth: 460,
    minHeight: 450,
    singleton: true,
    dockItem: false,
    desktopItem: false,
    description: 'Create or edit projects in the Supabase database',
  },
  about: {
    id: 'about',
    name: 'About Me',
    icon: 'user',
    defaultTitle: 'About Harshit',
    defaultWidth: 680,
    defaultHeight: 520,
    minWidth: 440,
    minHeight: 360,
    singleton: true,
    dockItem: true,
    desktopItem: true,
    description: 'Bio, background, and technical skillset',
  },
  resume: {
    id: 'resume',
    name: 'Resume.pdf',
    icon: 'file-text',
    defaultTitle: 'Resume.pdf — Preview',
    defaultWidth: 800,
    defaultHeight: 650,
    minWidth: 480,
    minHeight: 420,
    singleton: true,
    dockItem: true,
    desktopItem: true,
    description: 'Curriculum Vitae and credentials',
  },
  contact: {
    id: 'contact',
    name: 'Contact',
    icon: 'mail',
    defaultTitle: 'Contact Harshit',
    defaultWidth: 580,
    defaultHeight: 460,
    minWidth: 400,
    minHeight: 340,
    singleton: true,
    dockItem: true,
    desktopItem: true,
    description: 'Get in touch via email or social networks',
  },
  terminal: {
    id: 'terminal',
    name: 'Terminal',
    icon: 'terminal',
    defaultTitle: 'harshit@macbook: ~ (zsh)',
    defaultWidth: 720,
    defaultHeight: 440,
    minWidth: 460,
    minHeight: 300,
    singleton: true,
    dockItem: true,
    desktopItem: false,
    description: 'Interactive portfolio command-line interface',
  },
  safari: {
    id: 'safari',
    name: 'Safari',
    icon: 'compass',
    defaultTitle: 'Safari — Web Browser',
    defaultWidth: 880,
    defaultHeight: 560,
    minWidth: 480,
    minHeight: 360,
    singleton: false,
    dockItem: true,
    desktopItem: false,
    description: 'Explore live web previews and resources',
  },
  settings: {
    id: 'settings',
    name: 'Settings',
    icon: 'settings',
    defaultTitle: 'System Settings',
    defaultWidth: 620,
    defaultHeight: 460,
    minWidth: 400,
    minHeight: 320,
    singleton: true,
    dockItem: false,
    desktopItem: false,
    description: 'Configure desktop wallpaper and preferences',
  },
}

export const INITIAL_DESKTOP_ITEMS: DesktopItem[] = [
  {
    id: 'desktop-projects',
    name: 'Projects',
    type: 'folder',
    appId: 'finder',
    icon: 'folder',
    x: 24,
    y: 28,
  },
  {
    id: 'desktop-resume',
    name: 'Resume.pdf',
    type: 'file',
    appId: 'resume',
    icon: 'file-text',
    x: 24,
    y: 132,
  },
  {
    id: 'desktop-about',
    name: 'About Me',
    type: 'app',
    appId: 'about',
    icon: 'user',
    x: 24,
    y: 236,
  },
  {
    id: 'desktop-contact',
    name: 'Contact',
    type: 'app',
    appId: 'contact',
    icon: 'mail',
    x: 24,
    y: 340,
  },
]

export const DOCK_ITEMS: { appId: AppId; name: string; icon: string }[] = [
  { appId: 'finder', name: 'Finder', icon: 'finder' },
  { appId: 'safari', name: 'Safari', icon: 'compass' },
  { appId: 'about', name: 'About', icon: 'user' },
  { appId: 'resume', name: 'Resume', icon: 'file-text' },
  { appId: 'terminal', name: 'Terminal', icon: 'terminal' },
  { appId: 'contact', name: 'Mail', icon: 'mail' },
]
